# Project Name
TARGET = keyplayer

# Sources
CPP_SOURCES = keyplayer.cpp \
  AudioPath.cpp \
  Channel.cpp \
  Program.cpp \
  EnvelopeState.cpp \
  FmAlgorithm.cpp \
  FmOperator.cpp \
  MidiDispatcher.cpp \
  Voice.cpp 

# Library Locations
LIBDAISY_DIR = ../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
