# Project Name
TARGET = keyplayer

# Sources
CPP_SOURCES = keyplayer.cpp MidiDispatcher.cpp Voice.cpp FmOperator.cpp \
              AudioPath.cpp

# Library Locations
LIBDAISY_DIR = ../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
