# This Makefile (almost) follows the template in DaisyExamples
# also set LIBDAISY_DIR to point to where libDaisy is installed
# (../DaisyExamples/libDaisy in my case).
# See https://github.com/electro-smith/DaisyExamples
#
# I believe the included Makefile also expects:
# GCC_PATH
# OCD_DIR
# and they should be in PATH as well
#
# For further info on setting up the development environment for
# Daisy Seed, see:
# https://forum.electro-smith.com/t/welcome-to-daisy-get-started-here

# Project Name
TARGET = daisychain

# Sources
CPP_SOURCES = daisychain.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
